INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Item 1', 50);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Item 2', 100);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Item 3', 120);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Item 4', 150);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Item 5', 300);