DROP SCHEMA IF EXISTS chat CASCADE;

CREATE SCHEMA chat;

CREATE TABLE IF NOT EXISTS chat.users(
  id SERIAL PRIMARY KEY,
  login TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat.rooms(
  id    SERIAL PRIMARY KEY,
  name  TEXT NOT NULL,
  owner INTEGER NOT NULL REFERENCES chat.users(id)
);

CREATE TABLE IF NOT EXISTS chat.messages(
  id SERIAL PRIMARY KEY,
  author BIGINT REFERENCES chat.users(id) NOT NULL,
  room BIGINT REFERENCES chat.rooms(id) NOT NULL,
  text TEXT NOT NULL,
  time TIMESTAMP
);